services:
  # Raspberry Pi 5 specific device mappings
  traffic-monitor:
    devices:
      - /dev/gpiochip4:/dev/gpiochip4  # Pi 5 main GPIO chip (40-pin header)
      # Add camera device if needed:
      # - /dev/video0:/dev/video0

  dht22-weather:
    devices:
      - /dev/gpiochip4:/dev/gpiochip4  # Pi 5 GPIO access for DHT22 sensor
      
  # Add any Pi-specific volume overrides or additional services here
  # For example, if you need different paths on Pi:
  # traffic-monitor:
  #   volumes:
  #     - /boot/config.txt:/boot/config.txt:ro  # Read Pi config if needed