services:
  # Raspberry Pi 5 specific device mappings and GPIO access
  traffic-monitor:
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
      - /dev/gpiochip2:/dev/gpiochip2
      - /dev/gpiochip3:/dev/gpiochip3
      - /dev/gpiochip4:/dev/gpiochip4  # Pi 5 main GPIO chip (40-pin header)
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices/platform/soc:/sys/devices/platform/soc
    group_add:
      - gpio
    cap_add:
      - SYS_RAWIO

  dht22-weather:
    devices:
      - /dev/gpiochip0:/dev/gpiochip0
      - /dev/gpiochip1:/dev/gpiochip1
      - /dev/gpiochip2:/dev/gpiochip2
      - /dev/gpiochip3:/dev/gpiochip3
      - /dev/gpiochip4:/dev/gpiochip4  # Pi 5 GPIO access for DHT22 sensor
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /sys/devices/platform/soc:/sys/devices/platform/soc
    group_add:
      - gpio
    cap_add:
      - SYS_RAWIO

  # Add GPIO access to any other services that need hardware control
  airport-weather:
    devices:
      - /dev/gpiochip4:/dev/gpiochip4
    volumes:
      - /sys/class/gpio:/sys/class/gpio
    group_add:
      - gpio
    cap_add:
      - SYS_RAWIO

  data-maintenance:
    devices:
      - /dev/gpiochip4:/dev/gpiochip4
    volumes:
      - /sys/class/gpio:/sys/class/gpio
    group_add:
      - gpio
    cap_add:
      - SYS_RAWIO