services:
  # Raspberry Pi 5 specific device mappings and hardware access
  traffic-monitor:
    devices:
      - /dev/gpiochip4:/dev/gpiochip4  # Pi 5 main GPIO chip (40-pin header)
      - /dev/video0:/dev/video0        # Primary camera device
      - /dev/video10:/dev/video10      # IMX500 neural processor input
      - /dev/video11:/dev/video11      # IMX500 neural processor output
      - /dev/dri:/dev/dri             # GPU access for libcamera
    volumes:
      - /sys/class/gpio:/sys/class/gpio
      - /opt/vc:/opt/vc:ro            # VideoCore libraries for camera
      - /sys/bus/i2c:/sys/bus/i2c:ro  # I2C bus access for camera control
    group_add:
      - gpio
      - video
    cap_add:
      - SYS_RAWIO
    environment:
      - LIBCAMERA_LOG_LEVELS=*:INFO
      - PI5_CAMERA_ENABLED=true
    privileged: true  # Required for libcamera hardware access

  dht22-weather:
    devices:
      - /dev/gpiochip4:/dev/gpiochip4  # Pi 5 GPIO access for DHT22 sensor
    volumes:
      - /sys/class/gpio:/sys/class/gpio
    group_add:
      - gpio
    cap_add:
      - SYS_RAWIO

  # Add GPIO access to any other services that need hardware control
  airport-weather:
    devices:
      - /dev/gpiochip4:/dev/gpiochip4
    volumes:
      - /sys/class/gpio:/sys/class/gpio
    group_add:
      - gpio
    cap_add:
      - SYS_RAWIO

  data-maintenance:
    command: ["bash", "/app/scripts/start-with-maintenance.sh"]
    devices:
      - /dev/gpiochip4:/dev/gpiochip4
    volumes:
      - /sys/class/gpio:/sys/class/gpio
    group_add:
      - gpio
    cap_add:
      - SYS_RAWIO
    environment:
      - MAINTENANCE_IMAGE_MAX_AGE_HOURS=24
      - MAINTENANCE_SNAPSHOT_MAX_AGE_HOURS=168
      - MAINTENANCE_LOG_MAX_AGE_DAYS=30
      - MAINTENANCE_EMERGENCY_THRESHOLD=90
      - MAINTENANCE_WARNING_THRESHOLD=80